services:
  neo4j:
    image: neo4j:5.18
    environment:
      - NEO4J_AUTH=neo4j/strongpass123
    ports:
      - "7474:7474"
      - "7687:7687"
    volumes:
      - neo4j_data:/data
    healthcheck:
      test: ["CMD-SHELL", "wget --no-verbose --tries=1 --spider http://localhost:7474 || exit 1"]
      interval: 10s
      timeout: 5s
      retries: 5

  app:
    build: .
    environment:
      - NEO4J_URI=bolt://neo4j:7687
      - NEO4J_USER=neo4j
      - NEO4J_PASSWORD=strongpass123
      - GROQ_API_KEY=your_groq_api_key_here
      - OLLAMA_HOST=http://host.docker.internal:11434
      - PYTHONPATH=/app
    ports:
      - "8501:8501"
    volumes:
      - ./outputs:/app/outputs
    depends_on:
      neo4j:
        condition: service_healthy
    extra_hosts:
      - "host.docker.internal:host-gateway"

volumes:
  neo4j_data:
